# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Jorie Knook
tagline:             'PhD Student'
description:         '<img src="jorie_K.jpg" alt="jorie"> PhD student at the University of Edinburgh and SRUC. Working on Agriculture Economics'
url:                 https://jorieknook.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

github:
  repo:           https://github.com/jorieknook
